### ISSUE TITLE
关于评论区搜索评论的功能建议

### ISSUE THREAD

**Issue by KANA108** [imba97/Btools#1]
评论区搜索到评论后能不能添加自动定位到评论的功能，目前我有一个这方面功能的需要，需要在搜索出的的制定楼层下进行回复，但是由于没法定位到楼层的关系回复不了，或者不定位到楼层也可以，显示楼层是第几页第几行方便查找，谢谢。

**Comment by imba97** [comment]
这个之前做过，后来B站评论改版，楼层数没了，就没法根据楼层算出在哪一页了，后来就不了了之了。刚才又想到个方法，最近会尝试一下。

**Comment by imba97** [comment]
OK了 之后是优化显示效果 [详情](http://t.bilibili.com/311588396883006081)
