### ISSUE TITLE
b站自带笔记功能在打字时与助手快捷键冲突

### ISSUE THREAD

**Issue by NaTouY** [imba97/Btools#12]
虽说b站笔记常从记事本copy，但是还是有临时修改需求。但是在写笔记界面助手快捷键依旧激活,严重影响了打字（比如打字时突然f全屏到视频界面）

**Comment by imba97** [comment]
没太懂，Btools 的快捷键菜单不是需要长按才会显示吗，怎么造成的打字的时候冲突的

**Comment by NaTouY** [comment]
> 没太懂，Btools 的快捷键菜单不是需要长按才会显示吗，怎么造成的打字的时候冲突的
看到这句话去检查了一下。发现不是btool的问题。
我是小丑;_;

**Comment by imba97** [comment]
好嘞，那先关掉了
