### ISSUE TITLE
增强收藏夹的功能新版本哔哩哔哩网页似乎不可用

### ISSUE THREAD

**Issue by KANA108** [imba97/Btools#2]
增强收藏夹的功能新版本哔哩哔哩网页似乎用不了
![Snipaste_2019-10-18_09-43-56](https://user-images.githubusercontent.com/55820158/67059482-deaae280-f18b-11e9-8449-6f4523c42a50.png)

**Comment by KANA108** [comment]
操作上的问题，这块没有问题

**Comment by imba97** [comment]
> 操作上的问题，这块没有问题

emmmm 没问题？新版可能是只推送给部分用户，我这边还不是新版看不了

**Comment by imba97** [comment]
用上新版了，但收藏夹页面还是原版的，没啥问题。
